### ISSUE TITLE
anchors now being generated

### ISSUE THREAD

**Issue by dsyme** [fsharp/docs#24]
Just to note that the URLs in the search index generated by ApiDocs.GenerateSeachIndexFromModel have anchors.

SO if you're going to generate your own HTML you should make sure the anchors get emitted.

e.g https://dsyme.github.io/DiffSharp/reference/diffsharp-tensor.html#leakyRelu

**Comment by cartermp** [comment]
Oh fantastic. Definitely needed for some of the longer pages

**Comment by baronfel** [comment]
Yep, I have ids on elements already in this repo, but hadn't synced up the search index links with them yet. I'll make sure what's here is in line with the search index

**Comment by dsyme** [comment]
> Yep, I have ids on elements already in this repo, but hadn't synced up the search index links with them yet. I'll make sure what's here is in line with the search index

TBH I'm thinking we should just generate the whole site using the default `fsdocs` tooling (with a different template) now and iterate on that to make sure it's right.

There's nothing that special about FSharp.Core.  The default tooling should be able to do a great job on it, and any improvements we make will flow to everyone then

**Comment by cartermp** [comment]
The default template is rather nice. Wouldn't mind at least seeing what it looks like.

**Comment by dsyme** [comment]
> The default template is rather nice. Wouldn't mind at least seeing what it looks like.

I'd really like us to do a visual refresh of the default template as part of this general revamp, and push it out across most the sites.

**Comment by dsyme** [comment]
> The default template is rather nice. Wouldn't mind at least seeing what it looks like.

https://fsharp.github.io/fsharp-core-api-docs/
